#+TITLE:       The Common Lisp Condition System review
#+AUTHOR:      
#+EMAIL:       shka@tuxls
#+DATE:        2020-11-25 śro
#+URI:         /blog/%y/%m/%d/the-common-lisp-condition-system-review
#+KEYWORDS:    lisp, books
#+TAGS:        lisp, books
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Phoe wrote a book!
Phoe wrote and published a book. Given how deeply I've stuck in the Common Lisp rabbit hole I had to read and review it.

The first things first: is it worth reading? My answer is the clean and sound yes. The content of the book is a complete tour of all stack manipulation facilities of the language. Eventually, the book goes into implementing the whole condition system from the base elements. You truly can't get more Lisp than this. 

This is not the right book for the novice, but I am sure that it never aspired to be one. There is nothing to criticize in this approach. However, I have other things to complain about, because let me tell you: this is not an easy book to get through even for readers decently familiar with the subject. It boils down to style.

Text is convoluted, paragraphs seem to be chaotic and poorly laid out. I had to frequently u-turn and read a sentence from the beginning to get a good grasp of the text message. For instance, consider the following fragment: "It also means, indirectly, that dynamic variables give us way...". This simply does not flow, and sentence structures like that are the norm. Luckily for the reader phoe uses colloquial language. Small mercies.

Other than the above: I would love to see a chapter regarding practical design considerations while using lisp conditions. In fact, I would love to read a "Practical Design Considerations for Common Lisp Systems" book in general. Maybe something that phoe can work on in the future? Heck, I would gladly coauthor it. 

Anyway, grab yourself "The Common Lisp Condition System" and read it. You will learn a thing or two and it will hurt just a little bit.
